# Permalinks
permalink:      /:year/:month/:day/:title

# Setup
title:          AI-Ops
tagline:        UnionPay Machine Learn Lab
paginate:       5
baseurl:        "/blog"
url:            "https://yougzhao.github.com/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Chester How
  url:          http://chester.how
  email:        chesterhow@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
plugins:
  - jekyll-paginate
